<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvincesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinces = [
            ['id' => 101,'province' => 'Chachapoyas','department_id' => 1],
            ['id' => 102,'province' => 'Bagua','department_id' => 1],
            ['id' => 103,'province' => 'Bongará','department_id' => 1],
            ['id' => 104,'province' => 'Condorcanqui','department_id' => 1],
            ['id' => 105,'province' => 'Luya','department_id' => 1],
            ['id' => 106,'province' => 'Rodríguez de Mendoza','department_id' => 1],
            ['id' => 107,'province' => 'Utcubamba','department_id' => 1],
            ['id' => 201,'province' => 'Huaraz','department_id' => 2],
            ['id' => 202,'province' => 'Aija','department_id' => 2],
            ['id' => 203,'province' => 'Antonio Raymondi','department_id' => 2],
            ['id' => 204,'province' => 'Asunción','department_id' => 2],
            ['id' => 205,'province' => 'Bolognesi','department_id' => 2],
            ['id' => 206,'province' => 'Carhuaz','department_id' => 2],
            ['id' => 207,'province' => 'Carlos Fermín Fitzcarrald','department_id' => 2],
            ['id' => 208,'province' => 'Casma','department_id' => 2],
            ['id' => 209,'province' => 'Corongo','department_id' => 2],
            ['id' => 210,'province' => 'Huari','department_id' => 2],
            ['id' => 211,'province' => 'Huarmey','department_id' => 2],
            ['id' => 212,'province' => 'Huaylas','department_id' => 2],
            ['id' => 213,'province' => 'Mariscal Luzuriaga','department_id' => 2],
            ['id' => 214,'province' => 'Ocros','department_id' => 2],
            ['id' => 215,'province' => 'Pallasca','department_id' => 2],
            ['id' => 216,'province' => 'Pomabamba','department_id' => 2],
            ['id' => 217,'province' => 'Recuay','department_id' => 2],
            ['id' => 218,'province' => 'Santa','department_id' => 2],
            ['id' => 219,'province' => 'Sihuas','department_id' => 2],
            ['id' => 220,'province' => 'Yungay','department_id' => 2],
            ['id' => 301,'province' => 'Abancay','department_id' => 3],
            ['id' => 302,'province' => 'Andahuaylas','department_id' => 3],
            ['id' => 303,'province' => 'Antabamba','department_id' => 3],
            ['id' => 304,'province' => 'Aymaraes','department_id' => 3],
            ['id' => 305,'province' => 'Cotabambas','department_id' => 3],
            ['id' => 306,'province' => 'Chincheros','department_id' => 3],
            ['id' => 307,'province' => 'Grau','department_id' => 3],
            ['id' => 401,'province' => 'Arequipa','department_id' => 4],
            ['id' => 402,'province' => 'Camaná','department_id' => 4],
            ['id' => 403,'province' => 'Caravelí','department_id' => 4],
            ['id' => 404,'province' => 'Castilla','department_id' => 4],
            ['id' => 405,'province' => 'Caylloma','department_id' => 4],
            ['id' => 406,'province' => 'Condesuyos','department_id' => 4],
            ['id' => 407,'province' => 'Islay','department_id' => 4],
            ['id' => 408,'province' => 'La Uniòn','department_id' => 4],
            ['id' => 501,'province' => 'Huamanga','department_id' => 5],
            ['id' => 502,'province' => 'Cangallo','department_id' => 5],
            ['id' => 503,'province' => 'Huanca Sancos','department_id' => 5],
            ['id' => 504,'province' => 'Huanta','department_id' => 5],
            ['id' => 505,'province' => 'La Mar','department_id' => 5],
            ['id' => 506,'province' => 'Lucanas','department_id' => 5],
            ['id' => 507,'province' => 'Parinacochas','department_id' => 5],
            ['id' => 508,'province' => 'Pàucar del Sara Sara','department_id' => 5],
            ['id' => 509,'province' => 'Sucre','department_id' => 5],
            ['id' => 510,'province' => 'Víctor Fajardo','department_id' => 5],
            ['id' => 511,'province' => 'Vilcas Huamán','department_id' => 5],
            ['id' => 601,'province' => 'Cajamarca','department_id' => 6],
            ['id' => 602,'province' => 'Cajabamba','department_id' => 6],
            ['id' => 603,'province' => 'Celendín','department_id' => 6],
            ['id' => 604,'province' => 'Chota','department_id' => 6],
            ['id' => 605,'province' => 'Contumazá','department_id' => 6],
            ['id' => 606,'province' => 'Cutervo','department_id' => 6],
            ['id' => 607,'province' => 'Hualgayoc','department_id' => 6],
            ['id' => 608,'province' => 'Jaén','department_id' => 6],
            ['id' => 609,'province' => 'San Ignacio','department_id' => 6],
            ['id' => 610,'province' => 'San Marcos','department_id' => 6],
            ['id' => 611,'province' => 'San Miguel','department_id' => 6],
            ['id' => 612,'province' => 'San Pablo','department_id' => 6],
            ['id' => 613,'province' => 'Santa Cruz','department_id' => 6],
            ['id' => 701,'province' => 'Prov. Const. del Callao','department_id' => 7],
            ['id' => 801,'province' => 'Cusco','department_id' => 8],
            ['id' => 802,'province' => 'Acomayo','department_id' => 8],
            ['id' => 803,'province' => 'Anta','department_id' => 8],
            ['id' => 804,'province' => 'Calca','department_id' => 8],
            ['id' => 805,'province' => 'Canas','department_id' => 8],
            ['id' => 806,'province' => 'Canchis','department_id' => 8],
            ['id' => 807,'province' => 'Chumbivilcas','department_id' => 8],
            ['id' => 808,'province' => 'Espinar','department_id' => 8],
            ['id' => 809,'province' => 'La Convención','department_id' => 8],
            ['id' => 810,'province' => 'Paruro','department_id' => 8],
            ['id' => 811,'province' => 'Paucartambo','department_id' => 8],
            ['id' => 812,'province' => 'Quispicanchi','department_id' => 8],
            ['id' => 813,'province' => 'Urubamba','department_id' => 8],
            ['id' => 901,'province' => 'Huancavelica','department_id' => 9],
            ['id' => 902,'province' => 'Acobamba','department_id' => 9],
            ['id' => 903,'province' => 'Angaraes','department_id' => 9],
            ['id' => 904,'province' => 'Castrovirreyna','department_id' => 9],
            ['id' => 905,'province' => 'Churcampa','department_id' => 9],
            ['id' => 906,'province' => 'Huaytará','department_id' => 9],
            ['id' => 907,'province' => 'Tayacaja','department_id' => 9],
            ['id' => 1001,'province' => 'Huánuco','department_id' => 10],
            ['id' => 1002,'province' => 'Ambo','department_id' => 10],
            ['id' => 1003,'province' => 'Dos de Mayo','department_id' => 10],
            ['id' => 1004,'province' => 'Huacaybamba','department_id' => 10],
            ['id' => 1005,'province' => 'Huamalíes','department_id' => 10],
            ['id' => 1006,'province' => 'Leoncio Prado','department_id' => 10],
            ['id' => 1007,'province' => 'Marañón','department_id' => 10],
            ['id' => 1008,'province' => 'Pachitea','department_id' => 10],
            ['id' => 1009,'province' => 'Puerto Inca','department_id' => 10],
            ['id' => 1010,'province' => 'Lauricocha ','department_id' => 10],
            ['id' => 1011,'province' => 'Yarowilca ','department_id' => 10],
            ['id' => 1101,'province' => 'Ica ','department_id' => 11],
            ['id' => 1102,'province' => 'Chincha ','department_id' => 11],
            ['id' => 1103,'province' => 'Nasca ','department_id' => 11],
            ['id' => 1104,'province' => 'Palpa ','department_id' => 11],
            ['id' => 1105,'province' => 'Pisco ','department_id' => 11],
            ['id' => 1201,'province' => 'Huancayo ','department_id' => 12],
            ['id' => 1202,'province' => 'Concepción ','department_id' => 12],
            ['id' => 1203,'province' => 'Chanchamayo ','department_id' => 12],
            ['id' => 1204,'province' => 'Jauja ','department_id' => 12],
            ['id' => 1205,'province' => 'Junín ','department_id' => 12],
            ['id' => 1206,'province' => 'Satipo ','department_id' => 12],
            ['id' => 1207,'province' => 'Tarma ','department_id' => 12],
            ['id' => 1208,'province' => 'Yauli ','department_id' => 12],
            ['id' => 1209,'province' => 'Chupaca ','department_id' => 12],
            ['id' => 1301,'province' => 'Trujillo ','department_id' => 13],
            ['id' => 1302,'province' => 'Ascope ','department_id' => 13],
            ['id' => 1303,'province' => 'Bolívar ','department_id' => 13],
            ['id' => 1304,'province' => 'Chepén ','department_id' => 13],
            ['id' => 1305,'province' => 'Julcán ','department_id' => 13],
            ['id' => 1306,'province' => 'Otuzco ','department_id' => 13],
            ['id' => 1307,'province' => 'Pacasmayo ','department_id' => 13],
            ['id' => 1308,'province' => 'Pataz ','department_id' => 13],
            ['id' => 1309,'province' => 'Sánchez Carrión ','department_id' => 13],
            ['id' => 1310,'province' => 'Santiago de Chuco ','department_id' => 13],
            ['id' => 1311,'province' => 'Gran Chimú ','department_id' => 13],
            ['id' => 1312,'province' => 'Virú ','department_id' => 13],
            ['id' => 1401,'province' => 'Chiclayo ','department_id' => 14],
            ['id' => 1402,'province' => 'Ferreñafe ','department_id' => 14],
            ['id' => 1403,'province' => 'Lambayeque ','department_id' => 14],
            ['id' => 1501,'province' => 'Lima ','department_id' => 15],
            ['id' => 1502,'province' => 'Barranca ','department_id' => 15],
            ['id' => 1503,'province' => 'Cajatambo ','department_id' => 15],
            ['id' => 1504,'province' => 'Canta ','department_id' => 15],
            ['id' => 1505,'province' => 'Cañete ','department_id' => 15],
            ['id' => 1506,'province' => 'Huaral ','department_id' => 15],
            ['id' => 1507,'province' => 'Huarochirí ','department_id' => 15],
            ['id' => 1508,'province' => 'Huaura ','department_id' => 15],
            ['id' => 1509,'province' => 'Oyón ','department_id' => 15],
            ['id' => 1510,'province' => 'Yauyos ','department_id' => 15],
            ['id' => 1601,'province' => 'Maynas ','department_id' => 16],
            ['id' => 1602,'province' => 'Alto Amazonas ','department_id' => 16],
            ['id' => 1603,'province' => 'Loreto ','department_id' => 16],
            ['id' => 1604,'province' => 'Mariscal Ramón Castilla ','department_id' => 16],
            ['id' => 1605,'province' => 'Requena ','department_id' => 16],
            ['id' => 1606,'province' => 'Ucayali ','department_id' => 16],
            ['id' => 1607,'province' => 'Datem del Marañón ','department_id' => 16],
            ['id' => 1608,'province' => 'Putumayo','department_id' => 16],
            ['id' => 1701,'province' => 'Tambopata ','department_id' => 17],
            ['id' => 1702,'province' => 'Manu ','department_id' => 17],
            ['id' => 1703,'province' => 'Tahuamanu ','department_id' => 17],
            ['id' => 1801,'province' => 'Mariscal Nieto ','department_id' => 18],
            ['id' => 1802,'province' => 'General Sánchez Cerro ','department_id' => 18],
            ['id' => 1803,'province' => 'Ilo ','department_id' => 18],
            ['id' => 1901,'province' => 'Pasco ','department_id' => 19],
            ['id' => 1902,'province' => 'Daniel Alcides Carrión ','department_id' => 19],
            ['id' => 1903,'province' => 'Oxapampa ','department_id' => 19],
            ['id' => 2001,'province' => 'Piura ','department_id' => 20],
            ['id' => 2002,'province' => 'Ayabaca ','department_id' => 20],
            ['id' => 2003,'province' => 'Huancabamba ','department_id' => 20],
            ['id' => 2004,'province' => 'Morropón ','department_id' => 20],
            ['id' => 2005,'province' => 'Paita ','department_id' => 20],
            ['id' => 2006,'province' => 'Sullana ','department_id' => 20],
            ['id' => 2007,'province' => 'Talara ','department_id' => 20],
            ['id' => 2008,'province' => 'Sechura ','department_id' => 20],
            ['id' => 2101,'province' => 'Puno ','department_id' => 21],
            ['id' => 2102,'province' => 'Azángaro ','department_id' => 21],
            ['id' => 2103,'province' => 'Carabaya ','department_id' => 21],
            ['id' => 2104,'province' => 'Chucuito ','department_id' => 21],
            ['id' => 2105,'province' => 'El Collao ','department_id' => 21],
            ['id' => 2106,'province' => 'Huancané ','department_id' => 21],
            ['id' => 2107,'province' => 'Lampa ','department_id' => 21],
            ['id' => 2108,'province' => 'Melgar ','department_id' => 21],
            ['id' => 2109,'province' => 'Moho ','department_id' => 21],
            ['id' => 2110,'province' => 'San Antonio de Putina ','department_id' => 21],
            ['id' => 2111,'province' => 'San Román ','department_id' => 21],
            ['id' => 2112,'province' => 'Sandia ','department_id' => 21],
            ['id' => 2113,'province' => 'Yunguyo ','department_id' => 21],
            ['id' => 2201,'province' => 'Moyobamba ','department_id' => 22],
            ['id' => 2202,'province' => 'Bellavista ','department_id' => 22],
            ['id' => 2203,'province' => 'El Dorado ','department_id' => 22],
            ['id' => 2204,'province' => 'Huallaga ','department_id' => 22],
            ['id' => 2205,'province' => 'Lamas ','department_id' => 22],
            ['id' => 2206,'province' => 'Mariscal Cáceres ','department_id' => 22],
            ['id' => 2207,'province' => 'Picota ','department_id' => 22],
            ['id' => 2208,'province' => 'Rioja ','department_id' => 22],
            ['id' => 2209,'province' => 'San Martín ','department_id' => 22],
            ['id' => 2210,'province' => 'Tocache ','department_id' => 22],
            ['id' => 2301,'province' => 'Tacna ','department_id' => 23],
            ['id' => 2302,'province' => 'Candarave ','department_id' => 23],
            ['id' => 2303,'province' => 'Jorge Basadre ','department_id' => 23],
            ['id' => 2304,'province' => 'Tarata ','department_id' => 23],
            ['id' => 2401,'province' => 'Tumbes ','department_id' => 24],
            ['id' => 2402,'province' => 'Contralmirante Villar ','department_id' => 24],
            ['id' => 2403,'province' => 'Zarumilla ','department_id' => 24],
            ['id' => 2501,'province' => 'Coronel Portillo ','department_id' => 25],
            ['id' => 2502,'province' => 'Atalaya ','department_id' => 25],
            ['id' => 2503,'province' => 'Padre Abad ','department_id' => 25],
            ['id' => 2504,'province' => 'Purús','department_id' => 25]
        ];
        DB::table('provinces')->insert($provinces);
    }
}
